version: '3'
services:
  frontend:
    build:
      context: ./gredditfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./gredditbackend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
